
project_id = "xqfjyqukyahylbgbtxmg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.auth]
verify_jwt = true

[functions.api-key]
verify_jwt = true

[functions.gemini-api]
verify_jwt = false
