// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqfjyqukyahylbgbtxmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZmp5cXVreWFoeWxiZ2J0eG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTg3MDgsImV4cCI6MjA1OTA3NDcwOH0.kEyI2k3GfL5Q1-4t1Wjr8Wy2PzLANfsqrmWFsRn9JW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);